Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 252, in fetch_command
    app_name = get_commands()[subcommand]
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 101, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 93, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/app_bestgames/bestgames/src/com/thebridgestudio/FollowApi/FollowApi/settings.py", line 104, in <module>
    PROJECT_FOLDER = os.path.dirname(os.path.dirname(os.path.normpath(__file__)))
NameError: name 'os' is not defined
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
[21/Feb/2013 08:03:59] "GET / HTTP/1.0" 500 59137
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
[21/Feb/2013 08:04:59] "GET / HTTP/1.0" 200 2
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
[21/Feb/2013 08:28:04] "GET / HTTP/1.0" 200 119
[21/Feb/2013 08:28:08] "GET / HTTP/1.0" 200 119
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
[21/Feb/2013 08:55:25] "GET /follow HTTP/1.0" 500 96828
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
[21/Feb/2013 08:56:10] "GET /follow HTTP/1.0" 500 62776
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <bound method Command.inner_run of <django.contrib.staticfiles.management.commands.runserver.Command object at 0x2ac45d0>>
Validating models...

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 91, in inner_run
    self.validate(display_num_errors=True)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/validation.py", line 30, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/usr/local/lib/python2.7/site-packages/django/db/models/loading.py", line 158, in get_app_errors
    self._populate()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/loading.py", line 64, in _populate
    self.load_app(app_name, True)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/loading.py", line 88, in load_app
    models = import_module('.models', app_name)
  File "/usr/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/app_bestgames/bestgames/src/com/thebridgestudio/FollowApi/Operations/models.py", line 6, in <module>
    class Operation(models.Model):
  File "/home/app_bestgames/bestgames/src/com/thebridgestudio/FollowApi/Operations/models.py", line 8, in Operation
    addTime = models.DateTimeField(default=datetime.now)
NameError: name 'datetime' is not defined
[21/Feb/2013 09:37:51] "GET /add HTTP/1.0" 500 84296
[21/Feb/2013 09:38:17] "GET / HTTP/1.0" 200 119
[21/Feb/2013 09:38:29] "GET /add HTTP/1.0" 500 84374
[21/Feb/2013 09:42:55] "GET /follow HTTP/1.0" 200 3
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
Error: That port is already in use.
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
[22/Feb/2013 08:27:49] "GET / HTTP/1.0" 200 128
[22/Feb/2013 08:27:57] "GET /follow HTTP/1.0" 200 3
[22/Feb/2013 08:27:59] "GET /follow HTTP/1.0" 200 3
[22/Feb/2013 08:29:09] "GET /follow HTTP/1.0" 200 3
[22/Feb/2013 08:29:12] "GET /follow HTTP/1.0" 200 3
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
[22/Feb/2013 08:31:43] "GET /follow HTTP/1.0" 500 62355
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
[22/Feb/2013 08:33:50] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 08:33:55] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 08:34:05] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 09:03:36] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 09:08:37] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 09:11:42] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 09:13:25] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 09:15:49] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:12:53] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:13:38] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:15:11] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:15:13] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:15:16] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:15:17] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:15:19] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:15:21] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:15:23] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:15:25] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:15:27] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:15:28] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:15:30] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:15:32] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:15:34] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:15:36] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:15:38] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:15:40] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:15:42] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:15:43] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:15:45] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:19:59] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:22:07] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:25:05] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:25:10] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:25:14] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:25:20] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:25:25] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:25:29] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:25:34] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:25:39] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:25:44] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:25:49] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:25:54] "GET /follow HTTP/1.0" 200 12
[22/Feb/2013 17:25:59] "GET /follow HTTP/1.0" 200 12
[23/Feb/2013 08:52:36] "GET /follow HTTP/1.0" 200 12
[23/Feb/2013 08:52:40] "GET /follow HTTP/1.0" 200 12
[23/Feb/2013 08:52:46] "GET /follow HTTP/1.0" 200 12
[23/Feb/2013 08:52:51] "GET /follow HTTP/1.0" 200 12
[23/Feb/2013 08:52:56] "GET /follow HTTP/1.0" 200 12
[23/Feb/2013 08:53:01] "GET /follow HTTP/1.0" 200 12
[23/Feb/2013 21:52:11] "GET /follow HTTP/1.0" 200 12
[23/Feb/2013 21:52:17] "GET /follow HTTP/1.0" 200 12
[23/Feb/2013 21:52:21] "GET /follow HTTP/1.0" 200 12
[23/Feb/2013 21:52:26] "GET /follow HTTP/1.0" 200 12
[23/Feb/2013 21:52:31] "GET /follow HTTP/1.0" 200 12
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
[24/Feb/2013 00:44:16] "POST /finish_follow HTTP/1.0" 404 2149
[24/Feb/2013 00:44:16] "GET /follow HTTP/1.0" 500 86622
[24/Feb/2013 00:45:25] "GET /follow HTTP/1.0" 500 86622
[24/Feb/2013 00:45:44] "POST /finish_follow HTTP/1.0" 404 2149
[24/Feb/2013 00:45:44] "GET /follow HTTP/1.0" 500 87597
[24/Feb/2013 00:46:22] "POST /finish_follow HTTP/1.0" 404 2149
[24/Feb/2013 00:46:22] "GET /follow HTTP/1.0" 500 87729
[24/Feb/2013 00:47:51] "POST /finish_follow HTTP/1.0" 404 2149
[24/Feb/2013 00:47:51] "GET /follow HTTP/1.0" 500 87300
[24/Feb/2013 00:48:34] "GET / HTTP/1.0" 200 128
[24/Feb/2013 00:48:42] "GET /follow HTTP/1.0" 500 86597
[24/Feb/2013 00:49:40] "GET /follow HTTP/1.0" 200 12
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
[24/Feb/2013 00:51:03] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:51:15] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:51:26] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:51:38] "POST /finish_follow HTTP/1.0" 403 2282
[24/Feb/2013 00:51:38] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:51:49] "POST /finish_follow HTTP/1.0" 403 2282
[24/Feb/2013 00:51:49] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:52:00] "POST /finish_follow HTTP/1.0" 403 2282
[24/Feb/2013 00:52:00] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:52:11] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:52:21] "GET /finish_follow HTTP/1.0" 500 62863
[24/Feb/2013 00:52:23] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:52:34] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:52:44] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:52:56] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:53:06] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:53:18] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:53:29] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:53:40] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:53:52] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:54:03] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:54:13] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:54:24] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:54:35] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:54:46] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:54:57] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:55:08] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:55:20] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:55:31] "GET /follow HTTP/1.0" 200 12
[24/Feb/2013 00:55:42] "GET /follow HTTP/1.0" 200 12
Validating models...

0 errors found
Django version 1.4.3, using settings 'FollowApi.settings'
Development server is running at http://127.0.0.1:7998/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 252, in fetch_command
    app_name = get_commands()[subcommand]
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 101, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 93, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/app_bestgames/bestgames/src/com/thebridgestudio/FollowApi/FollowApi/settings.py", line 153
    'default': {
            ^
SyntaxError: invalid syntax
